//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabalim.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Catalogos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Catalogos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tabalim.Data.Catalogos", typeof(Catalogos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Path&quot;:&quot;&quot;,&quot;Tableros&quot;:{},&quot;Lineas&quot;:{},&quot;ProjectName&quot;:&quot;TabalimNewApplication&quot;,&quot;Start&quot;:&quot;2017-10-09T00:00:00&quot;,&quot;Id&quot;:1,&quot;TableName&quot;:&quot;proyectos&quot;,&quot;PrimaryKey&quot;:&quot;prj_id&quot;}.
        /// </summary>
        internal static string empty_project {
            get {
                return ResourceManager.GetString("empty_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;KW&quot;:0.12,&quot;HP&quot;:0.16666,&quot;HPFormat&quot;:&quot;1/6 HP&quot;,&quot;I_1_127&quot;:4.0,&quot;I_1_230&quot;:2.2,&quot;I_2_115&quot;:-1.0,&quot;I_2_230&quot;:-1.0,&quot;I_2_460&quot;:-1.0,&quot;I_3_115&quot;:-1.0,&quot;I_3_208&quot;:-1.0,&quot;I_3_230&quot;:-1.0,&quot;I_3_460&quot;:-1.0},{&quot;KW&quot;:0.19,&quot;HP&quot;:0.25,&quot;HPFormat&quot;:&quot;1/4 HP&quot;,&quot;I_1_127&quot;:5.3,&quot;I_1_230&quot;:2.9,&quot;I_2_115&quot;:-1.0,&quot;I_2_230&quot;:-1.0,&quot;I_2_460&quot;:-1.0,&quot;I_3_115&quot;:-1.0,&quot;I_3_208&quot;:-1.0,&quot;I_3_230&quot;:-1.0,&quot;I_3_460&quot;:-1.0},{&quot;KW&quot;:0.25,&quot;HP&quot;:0.33333,&quot;HPFormat&quot;:&quot;1/3 HP&quot;,&quot;I_1_127&quot;:6.5,&quot;I_1_230&quot;:3.6,&quot;I_2_115&quot;:-1.0,&quot;I_2_230&quot;:-1.0,&quot;I_2_460&quot;:-1.0,&quot;I_3_115&quot;:-1.0,&quot;I_3_208&quot;:-1.0,&quot;I_3_230&quot;:- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hp_watts {
            get {
                return ResourceManager.GetString("hp_watts", resourceCulture);
            }
        }
    }
}
